export const buyedCourse = {
  id: "course-1",
  titleRu: "Прикорм без проблем",
  titleUz: "Qo'shimcha muammosiz ovqatlar",
  descriptionRu: "Небольшое описание про этот курс в 1 строк!",
  descriptionUz: "Ushbu kurs haqida 1 satrdan iborat kichik tavsif!",
};

export const modules = [
  {
    id: "module-1",
    titleRu: "Модуль 1",
    titleUz: "Modul 1",
    lessons: [
      {
        id: "lesson-1-ru",
        titleRu: "Урок 1",
        titleUz: "Урок 1",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/RUS/1-1.mp4",
      },
      {
        id: "lesson-1-uz",
        titleRu: "Dars 1",
        titleUz: "Dars 1",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/UZB/U1-1.mp4",
      },
      {
        id: "lesson-2-ru",
        titleRu: "Урок 2",
        titleUz: "Урок 2",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/RUS/1-2.mp4",
      },
      {
        id: "lesson-2-uz",
        titleRu: "Dars 2",
        titleUz: "Dars 2",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/UZB/U1-2.mp4",
      },
      {
        id: "lesson-3-ru",
        titleRu: "Урок 3",
        titleUz: "Урок 3",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/RUS/1-3.mp4",
      },
      {
        id: "lesson-3-uz",
        titleRu: "Dars 3",
        titleUz: "Dars 3",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/UZB/U1-3.mp4",
      },
    ],
  },
  {
    id: "module-2",
    titleRu: "Модуль 2",
    titleUz: "Modul 2",
    lessons: [
      {
        id: "lesson-1-ru",
        titleRu: "Урок 1",
        titleUz: "Урок 1",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/RUS/2-1.mp4",
      },
      {
        id: "lesson-1-uz",
        titleRu: "Dars 1",
        titleUz: "Dars 1",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/UZB/U2-1.mp4",
      },
      {
        id: "lesson-2-ru",
        titleRu: "Урок 2",
        titleUz: "Урок 2",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/RUS/2-2.mp4",
      },
      {
        id: "lesson-2-uz",
        titleRu: "Dars 2",
        titleUz: "Dars 2",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/UZB/U2-2.mp4",
      },
      {
        id: "lesson-3-ru",
        titleRu: "Урок 3",
        titleUz: "Урок 3",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/RUS/2-3.mp4",
      },
      {
        id: "lesson-3-uz",
        titleRu: "Dars 3",
        titleUz: "Dars 3",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/UZB/U2-3.mp4",
      },
      {
        id: "lesson-4-ru",
        titleRu: "Урок 4",
        titleUz: "Урок 4",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/RUS/2-4.mp4",
      },
      {
        id: "lesson-4-uz",
        titleRu: "Dars 4",
        titleUz: "Dars 4",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/UZB/U2-4.mp4",
      },
      {
        id: "lesson-5-ru",
        titleRu: "Урок 5",
        titleUz: "Урок 5",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/RUS/2-5.mp4",
      },
      {
        id: "lesson-5-uz",
        titleRu: "Dars 5",
        titleUz: "Dars 5",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/UZB/U2-5.mp4",
      },
    ],
  },
  {
    id: "module-3",
    titleRu: "Модуль 3",
    titleUz: "Modul 3",
    lessons: [
      {
        id: "lesson-1-ru",
        titleRu: "Урок 1",
        titleUz: "Урок 1",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/RUS/3-1.mp4",
      },
      {
        id: "lesson-1-uz",
        titleRu: "Dars 1",
        titleUz: "Dars 1",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/UZB/U3-1.mp4",
      },
      {
        id: "lesson-2-ru",
        titleRu: "Урок 2",
        titleUz: "Урок 2",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/RUS/3-2.mp4",
      },
      {
        id: "lesson-2-uz",
        titleRu: "Dars 2",
        titleUz: "Dars 2",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/UZB/U3-2.mp4",
      },
      {
        id: "lesson-3-ru",
        titleRu: "Урок 3",
        titleUz: "Урок 3",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/RUS/3-3.mp4",
      },
      {
        id: "lesson-3-uz",
        titleRu: "Dars 3",
        titleUz: "Dars 3",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/UZB/U3-3.mp4",
      },
    ],
  },
  {
    id: "module-4",
    titleRu: "Модуль 4",
    titleUz: "Modul 4",
    lessons: [
      {
        id: "lesson-1-ru",
        titleRu: "Урок 1",
        titleUz: "Урок 1",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/RUS/4-1.mp4",
      },
      {
        id: "lesson-1-uz",
        titleRu: "Dars 1",
        titleUz: "Dars 1",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/UZB/U4-1.mp4",
      },
      {
        id: "lesson-2-ru",
        titleRu: "Урок 2",
        titleUz: "Урок 2",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/RUS/4-2.mp4",
      },
      {
        id: "lesson-2-uz",
        titleRu: "Dars 2",
        titleUz: "Dars 2",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/UZB/U4-2.mp4",
      },
      {
        id: "lesson-3-ru",
        titleRu: "Урок 3",
        titleUz: "Урок 3",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/RUS/4-3.mp4",
      },
      {
        id: "lesson-3-uz",
        titleRu: "Dars 3",
        titleUz: "Dars 3",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/UZB/U4-3.mp4",
      },
    ],
  },
  {
    id: "module-5",
    titleRu: "Модуль 5",
    titleUz: "Modul 5",
    lessons: [
      {
        id: "lesson-1-ru",
        titleRu: "Урок 1",
        titleUz: "Урок 1",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/RUS/5-1.mp4",
      },
      {
        id: "lesson-1-uz",
        titleRu: "Dars 1",
        titleUz: "Dars 1",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/UZB/U5-1.mp4",
      },
      {
        id: "lesson-2-ru",
        titleRu: "Урок 2",
        titleUz: "Урок 2",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/RUS/5-2.mp4",
      },
      {
        id: "lesson-2-uz",
        titleRu: "Dars 2",
        titleUz: "Dars 2",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/UZB/U5-2.mp4",
      },
      {
        id: "lesson-3-ru",
        titleRu: "Урок 3",
        titleUz: "Урок 3",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/RUS/5-3.mp4",
      },
      {
        id: "lesson-3-uz",
        titleRu: "Dars 3",
        titleUz: "Dars 3",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/UZB/U5-3.mp4",
      },
      {
        id: "lesson-4-ru",
        titleRu: "Урок 4",
        titleUz: "Урок 4",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/RUS/5-4.mp4",
      },
      {
        id: "lesson-4-uz",
        titleRu: "Dars 4",
        titleUz: "Dars 4",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/UZB/U5-4.mp4",
      },
    ],
  },
  {
    id: "module-6",
    titleRu: "Модуль 6",
    titleUz: "Modul 6",
    lessons: [
      {
        id: "lesson-1-ru",
        titleRu: "Урок 1",
        titleUz: "Урок 1",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/RUS/6-1.mp4",
      },
      {
        id: "lesson-1-uz",
        titleRu: "Dars 1",
        titleUz: "Dars 1",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/UZB/U6-1.mp4",
      },
      {
        id: "lesson-2-ru",
        titleRu: "Урок 2",
        titleUz: "Урок 2",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/RUS/6-2.mp4",
      },
      {
        id: "lesson-2-uz",
        titleRu: "Dars 2",
        titleUz: "Dars 2",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/UZB/U6-2.mp4",
      },
      {
        id: "lesson-3-ru",
        titleRu: "Урок 3",
        titleUz: "Урок 3",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/RUS/6-3.mp4",
      },
      {
        id: "lesson-3-uz",
        titleRu: "Dars 3",
        titleUz: "Dars 3",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/UZB/U6-3.mp4",
      },
    ],
  },
  {
    id: "module-7",
    titleRu: "Модуль 7",
    titleUz: "Modul 7",
    lessons: [
      {
        id: "lesson-1-ru",
        titleRu: "Урок 1",
        titleUz: "Урок 1",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/RUS/7-1.mp4",
      },
      {
        id: "lesson-1-uz",
        titleRu: "Dars 1",
        titleUz: "Dars 1",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/UZB/U7-1.mp4",
      },
      {
        id: "lesson-2-ru",
        titleRu: "Урок 2",
        titleUz: "Урок 2",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/RUS/7-2.mp4",
      },
      {
        id: "lesson-2-uz",
        titleRu: "Dars 2",
        titleUz: "Dars 2",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/UZB/U7-2.mp4",
      },
      {
        id: "lesson-3-ru",
        titleRu: "Урок 3",
        titleUz: "Урок 3",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/RUS/7-3.mp4",
      },
      {
        id: "lesson-3-uz",
        titleRu: "Dars 3",
        titleUz: "Dars 3",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/UZB/U7-3.mp4",
      },
    ],
  },
  {
    id: "module-8",
    titleRu: "Бонусное видео",
    titleUz: "Bonus video",
    lessons: [
      {
        id: "lesson-1-ru",
        titleRu: "Урок 1",
        titleUz: "Урок 1",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/RUS/Dop%20urok.mp4",
      },
      {
        id: "lesson-1-uz",
        titleRu: "Dars 1",
        titleUz: "Dars 1",
        link: "https://disk.yandex.ru/d/_S15C1naBRCscw/UZB/Dop%20urok%20UZ.mp4",
      },
    ],
  },
];
